### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by yangzhifeio** [ymxlzgy/echoscene#1]
Thanks for your great work! 

![image](https://github.com/ymxlzgy/echoscene/assets/49261029/86fb38f6-2c82-4354-8901-06d666fb1b3a)

Please tell me where the boxes_centered_stats_{}_trainval.txt file is located

thank you.

**Comment by ymxlzgy** [comment]
Sorry for the late update. The files can be downloaded [here](https://www.campar.in.tum.de/public_datasets/2024_echoscene/centered_bounds_3dfront.zip). These files can be available based on this [script](https://www.campar.in.tum.de/public_datasets/2023_commonscenes_zhai/script.zip), with which you calculate the minimum and maximum value of l,h,w,x,y,z in individual axis (including floor).

**Comment by karryyzf** [comment]
Thanks for your greate work!
May I ask if this code cannot be distributed during training?
Thanks！

**Comment by yangzhifeio** [comment]
Thanks for your greate work!
May I ask if this code cannot be distributed during training?
 @ymxlzgy 
Thanks！
