### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by yangzhifeio** [ymxlzgy/echoscene#2]
Thanks for your greate work!
May I ask if this code cannot be distributed during training?
Thanks！

**Comment by ymxlzgy** [comment]
Hi, thanks for the question. For now, this repo can only support one GPU training. Sorry about that. The bottleneck prohibiting it from being distributed is the GCN expression. I am also annoyed with it. But there might be a solution [here](https://github.com/ShunChengWu/3DSSG/blob/main/ssg/models/network_GNN.py). Can try to replace the GCN implemented in this repo with the one in the pointed repo.
