### ISSUE TITLE
Inference problem

### ISSUE THREAD

**Issue by yangzhifeio** [ymxlzgy/echoscene#4]
Thanks for your great work! I'm very interested in your work.
![SecondBedroom-6482](https://github.com/ymxlzgy/echoscene/assets/49261029/f5aecf91-8f23-4fd3-aabe-c242f96653c2)
I followed your inference code and adopted the full model 2050 provided by you to generate the above results. I would like to ask, the object in the render image of this topdown view is very small, how to adjust it to enlarge it. At the same time, in the follow-up FID/KID value calculation, is this render image also used? This picture is too small, and the resolution is very low.
Thanks!

**Comment by ymxlzgy** [comment]
You can adjust the height of your camera [here](https://github.com/ymxlzgy/echoscene/blob/d6ffdb7d11e33fc6da926567c8ab4a0aaf667434/helpers/visualize_scene.py#L132). If you adjust the height, you need to re-evaluate all methods for a fair comparison.

**Comment by mbwyjr** [comment]
May I ask if you obtained the top view through running the python train_3dfront.py --exp /path/to/exp_folder --room_type all --dataset /path/to/dataset --residual True --network_type echoscene --with_SDF True --with_CLIP True --batchSize 64 --workers 8 --loadmodel False --nepoch 10000 --large False --use_scene_rels True? Which folder is the generated scene saved in, or where is the path to save the scene set?
