### ISSUE TITLE
mapping_no_stool file not included

### ISSUE THREAD

**Issue by kangx326** [ymxlzgy/echoscene#5]
Hi, where can I access the 'mapping_no_stool.json' file?

**Comment by ymxlzgy** [comment]
That file is actually the `mapping.json` in the SG-FRONT. I will update the related part.

**Comment by 2741913295** [comment]
Hello, I still couldn't find the "mapping_no_stool.json" file in SG-FRONT. If you have time, could you please upload it? Thank you!
