### ISSUE TITLE
I want to know why there are no intermediate results in /echoscene/full_mp/diff_crossattn/images, and the contents of /echoscene/full_mp/diff_crossattn/loss_log.txt are as follows:

### ISSUE THREAD

**Issue by mbwyjr** [ymxlzgy/echoscene#7]
the contents of /echoscene/full_mp/diff_crossattn/loss_log.txt are as follows:
================ Training Loss (Wed Jun 19 18:45:31 2024) ================
python eval_3dfront.py --exp /mnt/second_drive/user_data/xqy/echoscene/scripts/checkpoint --dataset /mnt/second_drive/user_data/xqy/echoscene/FRONT --epoch 2050 --visualize True --room_type all --render_type echoscene --gen_shape True
my program's running status is:
1000it [01:29, 11.15it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (6, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:35<00:00,  2.85it/s]
rendering ['bed', 'nightstand', 'lamp', 'wardrobe', 'floor', '_scene_']
['MasterBedroom-34912']
inference mode, no gt boxes and scene ids
1000it [01:33, 10.73it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (9, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:49<00:00,  2.02it/s]
rendering ['table', 'nightstand', 'chair', 'bed', 'cabinet', 'lamp', 'wardrobe', 'floor', '_scene_']
['SecondBedroom-3960']
inference mode, no gt boxes and scene ids
1000it [01:28, 11.28it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (6, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:34<00:00,  2.86it/s]
rendering ['bed', 'nightstand', 'nightstand', 'wardrobe', 'floor', '_scene_']
['MasterBedroom-17206']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.79it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (10, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:52<00:00,  1.90it/s]
rendering ['bed', 'nightstand', 'wardrobe', 'chair', 'table', 'nightstand', 'lamp', 'tv_stand', 'floor', '_scene_']
['MasterBedroom-109561']
inference mode, no gt boxes and scene ids
1000it [01:41,  9.90it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (8, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:44<00:00,  2.23it/s]
rendering ['bed', 'lamp', 'tv_stand', 'chair', 'nightstand', 'wardrobe', 'floor', '_scene_']
['SecondBedroom-30334']
inference mode, no gt boxes and scene ids
1000it [01:41,  9.81it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (11, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:59<00:00,  1.69it/s]
rendering ['bed', 'wardrobe', 'wardrobe', 'nightstand', 'nightstand', 'chair', 'table', 'lamp', 'lamp', 'floor', '_scene_']
['Bedroom-54233']
inference mode, no gt boxes and scene ids
1000it [01:31, 10.94it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (9, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:49<00:00,  2.02it/s]
rendering ['wardrobe', 'bed', 'nightstand', 'nightstand', 'table', 'chair', 'lamp', 'floor', '_scene_']
['Bedroom-17102']
inference mode, no gt boxes and scene ids
1000it [01:29, 11.23it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (6, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:34<00:00,  2.86it/s]
rendering ['bed', 'table', 'lamp', 'wardrobe', 'floor', '_scene_']
['MasterBedroom-40319']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.84it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (10, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:52<00:00,  1.91it/s]
rendering ['wardrobe', 'lamp', 'lamp', 'lamp', 'table', 'bed', 'nightstand', 'nightstand', 'floor', '_scene_']
['MasterBedroom-28978']
inference mode, no gt boxes and scene ids
1000it [01:31, 10.89it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (9, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:49<00:00,  2.02it/s]
rendering ['nightstand', 'bookshelf', 'wardrobe', 'chair', 'desk', 'bed', 'lamp', 'floor', '_scene_']
['MasterBedroom-392']
inference mode, no gt boxes and scene ids
1000it [01:40, 10.00it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (9, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:49<00:00,  2.01it/s]
rendering ['wardrobe', 'nightstand', 'nightstand', 'nightstand', 'bed', 'bookshelf', 'lamp', 'floor', '_scene_']
['MasterBedroom-3712']
inference mode, no gt boxes and scene ids
1000it [01:28, 11.26it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (6, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:34<00:00,  2.86it/s]
rendering ['lamp', 'desk', 'chair', 'bed', 'floor', '_scene_']
['MasterBedroom-1446']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.78it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (9, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:49<00:00,  2.02it/s]
rendering ['bed', 'nightstand', 'wardrobe', 'lamp', 'chair', 'chair', 'chair', 'floor', '_scene_']
['SecondBedroom-6847']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.81it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (8, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:44<00:00,  2.24it/s]
rendering ['bed', 'cabinet', 'nightstand', 'nightstand', 'cabinet', 'lamp', 'floor', '_scene_']
['MasterBedroom-12183']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.79it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (8, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:44<00:00,  2.24it/s]
rendering ['desk', 'bed', 'nightstand', 'nightstand', 'lamp', 'lamp', 'floor', '_scene_']
['Bedroom-8136']
inference mode, no gt boxes and scene ids
1000it [01:29, 11.16it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (5, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:29<00:00,  3.37it/s]
rendering ['bed', 'wardrobe', 'lamp', 'floor', '_scene_']
['MasterBedroom-24714']
inference mode, no gt boxes and scene ids
1000it [01:29, 11.12it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (7, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:38<00:00,  2.60it/s]
rendering ['wardrobe', 'bed', 'tv_stand', 'nightstand', 'lamp', 'floor', '_scene_']
['Bedroom-13858']
inference mode, no gt boxes and scene ids
1000it [01:29, 11.13it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (7, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:38<00:00,  2.60it/s]
rendering ['bed', 'wardrobe', 'nightstand', 'nightstand', 'lamp', 'floor', '_scene_']
['MasterBedroom-118']
inference mode, no gt boxes and scene ids
1000it [01:28, 11.31it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (5, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:29<00:00,  3.37it/s]
rendering ['bed', 'table', 'lamp', 'floor', '_scene_']
['LivingRoom-37659']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.84it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (10, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:52<00:00,  1.91it/s]
rendering ['sofa', 'chair', 'chair', 'table', 'chair', 'table', 'table', 'lamp', 'floor', '_scene_']
['LivingRoom-1520']
inference mode, no gt boxes and scene ids
1000it [01:33, 10.71it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (14, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:12<00:00,  1.38it/s]
rendering ['sofa', 'table', 'tv_stand', 'chair', 'table', 'chair', 'chair', 'chair', 'chair', 'cabinet', 'lamp', 'lamp', 'floor', '_scene_']
['LivingRoom-17951']
inference mode, no gt boxes and scene ids
1000it [01:37, 10.23it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (6, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:35<00:00,  2.83it/s]
rendering ['sofa', 'table', 'tv_stand', 'lamp', 'floor', '_scene_']
['LivingDiningRoom-629']
inference mode, no gt boxes and scene ids
1000it [01:41,  9.82it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (16, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:23<00:00,  1.19it/s]
rendering ['sofa', 'tv_stand', 'desk', 'table', 'chair', 'chair', 'chair', 'chair', 'cabinet', 'bookshelf', 'chair', 'cabinet', 'lamp', 'lamp', 'floor', '_scene_']
['LivingRoom-71071']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.75it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (16, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:23<00:00,  1.20it/s]
rendering ['table', 'table', 'lamp', 'tv_stand', 'chair', 'chair', 'chair', 'chair', 'table', 'sofa', 'table', 'lamp', 'table', 'lamp', 'floor', '_scene_']
['LivingDiningRoom-9790']
inference mode, no gt boxes and scene ids
1000it [01:41,  9.86it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (14, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:12<00:00,  1.38it/s]
rendering ['sofa', 'tv_stand', 'cabinet', 'table', 'chair', 'chair', 'chair', 'chair', 'lamp', 'lamp', 'lamp', 'table', 'floor', '_scene_']
['LivingRoom-791']
inference mode, no gt boxes and scene ids
1000it [01:32, 10.77it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (15, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:18<00:00,  1.28it/s]
rendering ['table', 'chair', 'chair', 'chair', 'chair', 'sofa', 'tv_stand', 'table', 'table', 'table', 'lamp', 'lamp', 'lamp', 'floor', '_scene_']
['LivingRoom-24046']
inference mode, no gt boxes and scene ids
1000it [01:28, 11.24it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (7, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:38<00:00,  2.61it/s]
rendering ['bookshelf', 'sofa', 'table', 'lamp', 'chair', 'floor', '_scene_']
['LivingRoom-13599']
inference mode, no gt boxes and scene ids
1000it [01:35, 10.43it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (10, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:52<00:00,  1.91it/s]
rendering ['chair', 'chair', 'table', 'table', 'table', 'tv_stand', 'lamp', 'sofa', 'floor', '_scene_']
['LivingDiningRoom-13945']
inference mode, no gt boxes and scene ids
1000it [01:41,  9.82it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (15, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:18<00:00,  1.28it/s]
rendering ['sofa', 'chair', 'chair', 'chair', 'table', 'chair', 'lamp', 'chair', 'cabinet', 'table', 'shelf', 'lamp', 'tv_stand', 'floor', '_scene_']
['LivingDiningRoom-758']
inference mode, no gt boxes and scene ids
1000it [01:40,  9.92it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (12, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:04<00:00,  1.55it/s]
rendering ['lamp', 'table', 'chair', 'chair', 'lamp', 'lamp', 'sofa', 'table', 'tv_stand', 'table', 'floor', '_scene_']
['LivingRoom-33324']
inference mode, no gt boxes and scene ids
1000it [01:40,  9.90it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (9, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [00:49<00:00,  2.01it/s]
rendering ['tv_stand', 'table', 'sofa', 'table', 'chair', 'bookshelf', 'lamp', 'floor', '_scene_']
['LivingRoom-30147']
inference mode, no gt boxes and scene ids
1000it [01:34, 10.56it/s]
inference mode.. no gt sdf
Data shape for DDIM sampling is (20, 3, 16, 16, 16), eta 0.0
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|████████████████████████████████████████| 100/100 [01:41<00:00,  1.02s/it]
Traceback (most recent call last):
  File "eval_3dfront.py", line 412, in <module>
    evaluate()
  File "eval_3dfront.py", line 408, in evaluate
    validate_constrains_loop(modelArgs, test_dataset_no_changes, model, epoch=args.epoch, normalized_file=normalized_file, cat2objs=cat2objs, datasize='large' if modelArgs['large'] else 'small', gen_shape=args.gen_shape)
  File "eval_3dfront.py", line 271, in validate_constrains_loop
    data_dict = model.sample_box_and_shape(dec_objs, dec_triples, encoded_dec_text_feat, encoded_dec_rel_feat, gen_shape=gen_shape)
  File "/mnt/second_drive/user_data/xqy/echoscene/model/SGDiff.py", line 92, in sample_box_and_shape
    shape_dict, layout_dict = self.diff.sample(dec_objs, dec_triplets, encoded_dec_text_feat, encoded_dec_rel_feat, gen_shape=gen_shape)
  File "/mnt/second_drive/user_data/xqy/echoscene/model/EchoScene.py", line 418, in sample
    gen_sdf = self.ShapeDiff.rel2shape(shape_diff_dict)
  File "/mnt/second_drive/user_data/xqy/.conda/envs/echoscene/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/second_drive/user_data/xqy/echoscene/model/networks/diffusion_shape/echo2shape.py", line 522, in rel2shape
    self.gen_df = self.vqvae_module.decode_no_quant(samples)
  File "/mnt/second_drive/user_data/xqy/echoscene/model/networks/vqvae_networks/network.py", line 102, in decode_no_quant
    dec = self.decoder(quant)
  File "/mnt/second_drive/user_data/xqy/.conda/envs/echoscene/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/second_drive/user_data/xqy/echoscene/model/networks/vqvae_networks/vqvae_modules.py", line 395, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "/mnt/second_drive/user_data/xqy/.conda/envs/echoscene/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/second_drive/user_data/xqy/echoscene/model/networks/vqvae_networks/vqvae_modules.py", line 106, in forward
    h = nonlinearity(h)
  File "/mnt/second_drive/user_data/xqy/echoscene/model/networks/vqvae_networks/vqvae_modules.py", line 11, in nonlinearity
    return x*torch.sigmoid(x)
RuntimeError: CUDA out of memory. Tried to allocate 2.50 GiB (GPU 0; 15.78 GiB total capacity; 10.98 GiB already allocated; 1.56 GiB free; 13.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ymxlzgy** [comment]
Hi, actually this folder `diff_crossattn` is not necessary to be used. What do you want to observe btw?

**Comment by mbwyjr** [comment]
> 你好，其实这个文件夹`diff_crossattn`不是必须使用的。你还想观察什么？

I want to see the generated scenes, but I'm not sure how to do it, or input what scenes I want to generate. Can it generate scenes? How should I proceed?Thanks.

**Comment by ymxlzgy** [comment]
Hi. The scenes can be stored through [this line of code](https://github.com/ymxlzgy/echoscene/blob/fdc78e87fa88be6de744674c28fa86d1edd78f66/helpers/visualize_scene.py#L312). You need to name a path [here](https://github.com/ymxlzgy/echoscene/blob/fdc78e87fa88be6de744674c28fa86d1edd78f66/scripts/eval_3dfront.py#L377).
